### ISSUE TITLE
TDK-12-Kindle

### ISSUE THREAD

**Issue by bora-7** [anezih/guncel-turkce-sozluk-kindle-kobo-stardict#1]
Selam Nezih, bir arkadasim bahsettigi icin simdi yazidigin readme'yi gordum. Bilerek mi benim oradaki son mesajimi screenshot'a koymadin yoksa gormedin mi gercekten merak ettim 😄  Ben o mesaji yazdiktan sonra cevabini bekledim, cevap vermediginden dolayi issue'yi kapattim. Istersen bunu da ekle ya da ekleme, profesyonelligin yazdigin mesajlardan belli oluyor zaten.

![Screenshot_20240416-213907](https://github.com/anezih/guncel-turkce-sozluk-kindle-kobo-stardict/assets/76407294/e17448aa-1050-4158-8b60-ac137ac9ed32)

**Comment by anezih** [comment]
Selamlar, böyle bir harekette (issue'yu kapakmak yerine silmek) bulunacağınızı tahmin ettiğimden en son yazdığım yorumdan sonra ekran görüntüsü almıştım, tüm konuşmayı içeren ekran görüntüsünü almak için issue'ya tekrar uğradığımda silmiştiniz.
![image](https://github.com/anezih/guncel-turkce-sozluk-kindle-kobo-stardict/assets/90565940/c0310fd5-fb39-409b-9406-c337b07ce41c)
Tabii ki attığınız ekran görüntüsü kalabilir, issue'yu da tamamlandı olarak kapatıyorum (silmiyorum).

**Comment by bora-7** [comment]
Selam, benim son yazdığım mesaja "kaldırmanızı istiyorum" diye cevap vermeyip sonra kendi repo'nuzda gizlice README'yi güncellemeniz cidden ilginç, iyi bi güldürdü 😄. Sileceğimi tahmin etmiş olmanız büyük bir başarı değil, yazma tonunuzdan dolayı insanların sizinle muhatap olmayı istememelerini farketmişsinizdir.

Silme konusuna gelmişken, sizin Python betiğini kullarak yaptığım mobi dosyası silinmiş durumdadır. Önümüzdeki birkaç gün içerisinde sizin repo'nun linkini de README'den sileceğim.

Bu repo'da mesajları tutmakta iki şartla serbestsiniz:
1. mesajlar editlenmeyecek.
2. mesajların hepsi konulacak.

Tüm mesajların ekran görüntüsünü alıp sizinle iletişimi kesiyorum, benim repo'mda ileride açtığınız Issue'lar da silinecektir. Artık daha işe yarayan repo öne geçsin bakalım. Başarılar 👋 .

**Comment by anezih** [comment]
Gerekli atıfları tam bir şekilde yaptığınız sürece benim açımdan bir sorun yok. Yaptığınız işe de çok fazla karışmamak için "bunu kaldırın" tarzında bir cevap dönmedim. Kamuya açık bir repoda gizlice bir şeyler nasıl yapılıyor bilmiyorum ama bir jest olarak mesajları README'den kaldırayım. Comp. Sci.'da çok fazla paper yazıyor musunuz bilmiyorum ama bu atıf mevzusuna dikkat etmek önemli, ciddi sonuçları olabilir. Hayatta başarılar, yolunuz açık olsun.
